## Pytorch Introduction. 

### Checking the availability of CUDA.  
Having the CUDA support comes in handy when running neural networks on the local machines.  
Operations are much faster on GPU with parallel processing. Using the CPU is fine for basic models but at some point it will only be exhausting resources without doing much of the work.


In [1]:
import torch
print(torch.cuda.is_available())

True


## Tensor Operations 

In [7]:
from torch import tensor

In [ ]:
x = torch.rand((2,2))   # Create tensor of given size with random numbers [0,1)
                        # Can also use torch.ones() and torch.zeros() to create 
                        # tensors with 1's and 0's respectively 


print(x)
print(x.max())         # return the max val of the tensor.
print(x.argmax(dim=1)) # return indices of max vals along that dimension.


tensor([[0.2377, 0.2965],
        [0.0170, 0.8110]])
tensor(0.8110)
tensor([1, 1])


In [ ]:
x = tensor([[1,3,5],          # Convert multi-dimensional array into a tensor object 
                  [2,1,6],
                  [1,0,0]])

print("X is a : ",x.type())

x[0][1] = 0                 # Can access elements using standard python indexing

x



X is a :  torch.LongTensor


tensor([[1, 0, 5],
        [2, 1, 6],
        [1, 0, 0]])

In [ ]:
tensor([[1,3],[5,1]])*tensor([[1,2],[1,1]])     # Can perform standard mathematical operations 
                                                # on tensors like addition, multiplication etc.

tensor([[1, 6],
        [5, 1]])

In [ ]:
cpu_tensor = torch.rand(2)                          #GPU resources are scarce. If we want to utilize them 
                                                    # it need to be done explicitely. 

print("Created tensor in ",cpu_tensor.device)       # By default tensors are created in CPU 

gpu_tensor=cpu_tensor.to("cuda")                    # We can move them to gpu using tensor.to('cuda') and 
                                                    # we can bring them back to cpu using tensor.to('cpu')

print("Tensor moved to ",gpu_tensor.device)

Created tensor in  cpu
Tensor moved to  cuda:0


In [ ]:
x.exp_()  # functions with _ at end operate on the tensor without creating a copy

torch.FloatTensor


tensor([[1.2684, 1.3451],
        [1.0171, 2.2501]])

In [14]:
flat_tensor = torch.rand(3*28*28)       #We are creating a 1-D tensor
print(flat_tensor.shape)

#change the shape into a 3-D tensor
viewed_tensor = flat_tensor.reshape(3,28,28)  
print(viewed_tensor.shape)



torch.Size([2352])
torch.Size([3, 28, 28])


In [15]:
#change the order of shape

hwc_tensor = viewed_tensor.permute(1,2,0)
hwc_tensor.shape                

#This comes pretty handy when dealing with images. In the Image files Each pixel contains 
# its RGB values. But when processing we need to extract RGB channels seperatelt. We can 
# do that by using permutaions like in this example

torch.Size([28, 28, 3])